version: '3'

services:
  front_proxy:
    build: ./local/front
    container_name: front_proxy
    expose:
      - "8080"
      - "9900"
    ports:
      - "8080:8080"
      - "9900:9900"
    networks:
      - test-network
  post_proxy:
    build: ./local/post
    container_name: post_proxy
    expose:
      - "8081"
      - "9901"
    ports:
      - "9901:9901"
      - "8081:8081"
    networks:
      - test-network
  user_proxy:
    build: ./local/user
    container_name: user_proxy
    expose:
      - "8082"
      - "9902"
    ports:
      - "9902:9902"
      - "8082:8082"
    networks:
      - test-network
networks:
    test-network:
        external: true