# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
  aws-ecs: circleci/aws-ecs@1.1.0
# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  workflow:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only: master
          region: AWS_DEFAULT_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: ${ECR_REPOSITORY_NAME}
          tag: ${CIRCLE_SHA1}
      - aws-ecs/deploy-service-update:
          # イメージのビルド & プッシュが成功したら実行
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: master
          aws-region: ${AWS_DEFAULT_REGION}
          family: '${ECS_TASK}'
          cluster-name: '${ECS_CLUSTER}'
          service-name: '${ECS_SERVICE}'
          container-image-name-updates: 'container=${ECS_SERVICE},tag=${CIRCLE_SHA1},image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}'
